export default {
	FILTER_CONTAINER: 'FILTER_CONTAINER',
	FILTER_CONTAINER_TOGGLE: 'FILTER_CONTAINER_TOGGLE',
	MULTIPLE_CHOICE_FILTER_OPTION: 'MULTIPLE_CHOICE_FILTER_OPTION',
	TABLE_ROW: 'TABLE_ROW',
	MULTI_PASTE_INSERT_BUTTON: 'MULTI_PASTE_INSERT_BUTTON',
	MULTI_PASTE_SAVE_BUTTON: 'MULTI_PASTE_SAVE_BUTTON',
	LEHRENDE_NAME_ANZEIGE: 'LEHRENDE_NAME_ANZEIGE',
	DELETE_BUTTON: 'DELETE_BUTTON'
}
